### PR TITLE
Pull request for new documentation header

### PR DESCRIPTION
**Pull request by AnneDru**
Documentation header added 'Extension description'

### CODE REVIEW

**Comment by michaelmcandrew** [comment]
I can't see any changes - did you forget to include them?

**Comment by AnneDru** [comment]
Sorry Michael, here is the missing text .....

**Documentation header added 'Extension description'**

**Comment by michaelmcandrew** [comment]
hi @AnneDru 

thanks for the edits - very useful. I've made a couple of changes - i included the link to the already existing documentation and added a credits heading as well

**Comment by AnneDru** [comment]
Brill go ahead I think we're there

**Pull request merged**
